# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7)),
                ('image', models.ImageField(upload_to='dustbin')),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Contribution')),
                ('dustbin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Dustbin')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='waste')),
            ],
        ),
        migrations.AddField(
            model_name='trash',
            name='waste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Waste'),
        ),
    ]
