# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_auto_20161027_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waste',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
