# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 10:05
from __future__ import unicode_literals

from django.db import migrations
import datetime


def forward(apps, schema_editor):
    Legacy = apps.get_model("contributions", "Legacy")
    Trash = apps.get_model("contributions", "Trash")
    Contribution = apps.get_model("contributions", "Contribution")
    Waste = apps.get_model("contributions", "Waste")
    Dustbin = apps.get_model("contributions", "Dustbin")
    leg = Legacy.objects.all()
    Legacy.objects.filter(dechet_type=u"déchet alimentaire").update(dechet_type=u"dechet alimentaire")
    Legacy.objects.filter(dechet_type=u"déchet non recyclable").update(dechet_type=u"dechet non recyclable")
    for contrib in leg:
        timestamp = datetime.datetime.fromtimestamp(float(contrib.id_declarant))
        contribution, created = Contribution.objects.get_or_create(insee=contrib.code_insee, timestamp=timestamp)
        dustbin = Dustbin.objects.get(name__iexact=contrib.conteneur_couleur)
        waste = Waste.objects.get(name__iexact=contrib.dechet_type)
        trash = Trash(contribution=contribution, dustbin=dustbin, waste=waste)
        trash.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_auto_20161104_1005'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
