# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 16:51
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Commune = apps.get_model("contributions", "Commune")
    Contribution = apps.get_model("contributions", "Contribution")
    contributions = Contribution.objects.all()
    for contribution in contributions:
        commune, create = Commune.objects.get_or_create(insee=contribution.insee)
        contribution.commune = commune


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_auto_20161104_1651'),
    ]

    operations = [
    	migrations.RunPython(forward, backward),
    ]
