# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 16:56
from __future__ import unicode_literals

import requests
import json

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry, GeometryCollection


def forward(apps, schema_editor):
    Commune = apps.get_model("contributions", "Commune")
    communes = Commune.objects.all()
    for commune in communes:
        r = requests.get('https://geo.api.gouv.fr/communes?fields=contour&code=%s' % (commune.insee))
        try:
            coord = r.json()[0]['contour']
        except:
            pass
        try:
            mpoly = GEOSGeometry(json.dumps(coord))
            commune.geometry = GeometryCollection(mpoly)
            commune.save()
        except:
            pass

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_auto_20161104_1651'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
