# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 11:16
from __future__ import unicode_literals
import json
import os

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry, GeometryCollection


dir_path = os.path.dirname(os.path.realpath(__file__))

def forward(apps, schema_editor):
    path = os.path.join(dir_path, 'data', 'arrondissements.json')
    Commune = apps.get_model("contributions", "Commune")
    with open(path) as file:
        data = json.load(file)
        for feature in data['features']:
            insee = feature['properties']['insee']
            geometry = feature['geometry']
            commune, create = Commune.objects.get_or_create(insee=insee)
            mpoly = GEOSGeometry(json.dumps(geometry))
            commune.geometry = GeometryCollection(mpoly)
            commune.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_auto_20161104_1656'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
