# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_auto_20161114_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='slug',
            field=models.CharField(default='vide', max_length=100),
        ),
    ]
