# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_waste_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustbin',
            name='slug',
            field=models.CharField(default='vide', max_length=100),
        ),
    ]
