# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 09:39
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def loadfixture(apps, schema_editor):
    call_command('loaddata', 'data-slug.json')


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0014_dustbin_slug'),
    ]

    operations = [
        migrations.RunPython(loadfixture, backward),
    ]
